#!/bin/sh /etc/rc.common
# Copyright 2023-2024 sirpdboy team <herboy2008@gmail.com>

START=99
STOP=15
EXTRA_COMMANDS='reset'
EXTRA_HELP="Reset to default settings"

ipt=$(command -v iptables-legacy || command -v iptables)
ip6t=$(command -v ip6tables-legacy || command -v ip6tables)

reset() {
rm -rf /etc/config/advancedplus
cat <<EOF >/etc/config/advancedplus

config basic
	option gossr 'homeproxy'
	option gouser 'advancedplus'
	option gohome 'overview'
	option fontmode '0'
	option font_d '1.0rem'
	option font_z '0.9rem'
	option font_x '0.8rem'
	option bklock '1'
	option setbar '0'
	option dayword '0'
	option background '3'
	option bgqs '1'
	option bkuse '0'
	option mode 'auto'
	option primary_opacity '0'
	option primary_rgbm 'orange'
	option primary_rgbm_ts '0.9'
	option primary_rgbs '142,93,8'
	option primary_rgbs_ts '0.1'

config theme
	option bkuse '0'
	option mode 'auto'
	option primary_opacity '0'
	option primary_rgbm 'orange'
	option primary_rgbm_ts '0.9'
	option primary_rgbs '142,93,8'
	option primary_rgbs_ts '0.1'
	option remarks '桑迪布朗黄'
	option use '1'

config theme
	option bkuse '0'
	option mode 'dark'
	option primary_opacity '0'
	option primary_rgbm 'gray'
	option primary_rgbm_ts '0.9'
	option primary_rgbs '64,68,70'
	option primary_rgbs_ts '0.1'
	option remarks '炫酷黑夜时空'
	option use '0'

config theme
	option bkuse '0'
	option mode 'light'
	option primary_opacity '0'
	option primary_rgbm 'bluets'
	option primary_rgbm_ts '0.9'
	option primary_rgbs '55,103,128'
	option primary_rgbs_ts '0.1'
	option remarks '炫酷海洋之心'
	option use '0'

EOF
}

kucatset(){
	sum=$(grep -c 'theme' /etc/config/advancedplus)
	useset=0
	for i in $(seq 0 $((sum-1))) ; do
		use=$(uci -q get advancedplus.@theme[$i].use )
		if [ "x$use" == "x1" ]; then
			mode=`uci -q get advancedplus.@theme[$i].mode`
			primary_rgbm=`uci -q get advancedplus.@theme[$i].primary_rgbm`
			uci set advancedplus.@basic[0].mode=${mode}
			case "$primary_rgbm" in
				blue)
					uci set advancedplus.@basic[0].bkuse=`uci -q get advancedplus.@theme[$i].bkuse`
					uci set advancedplus.@basic[0].primary_opacity='0'
					uci set advancedplus.@basic[0].primary_rgbm='20,109,179'
					uci set advancedplus.@basic[0].primary_rgbm_ts='0.9'
					uci set advancedplus.@basic[0].primary_rgbs='28,66,188'
					uci set advancedplus.@basic[0].primary_rgbs_ts=`uci -q get advancedplus.@theme[$i].primary_rgbs_ts`
					[ $mode = dark ] && uci set advancedplus.@basic[0].primary_rgbbody='33,45,60' || uci set advancedplus.@basic[0].primary_rgbbody='248,248,248'
				;;
				green)
					uci set advancedplus.@basic[0].bkuse=`uci -q get advancedplus.@theme[$i].bkuse`
					uci set advancedplus.@basic[0].primary_opacity='0'
					uci set advancedplus.@basic[0].primary_rgbm='26,131,97'
					uci set advancedplus.@basic[0].primary_rgbm_ts='0.9'
					uci set advancedplus.@basic[0].primary_rgbs='76,157,69'
					uci set advancedplus.@basic[0].primary_rgbs_ts=`uci -q get advancedplus.@theme[$i].primary_rgbs_ts`
					[ $mode = dark ] && uci set advancedplus.@basic[0].primary_rgbbody='33,45,60' || uci set advancedplus.@basic[0].primary_rgbbody='248,248,248'
				;;
				orange)
					uci set advancedplus.@basic[0].bkuse=`uci -q get advancedplus.@theme[$i].bkuse`
					uci set advancedplus.@basic[0].primary_opacity='0'
					uci set advancedplus.@basic[0].primary_rgbm='163,71,6'
					uci set advancedplus.@basic[0].primary_rgbm_ts='0.9'
					uci set advancedplus.@basic[0].primary_rgbs='142,93,8'
					uci set advancedplus.@basic[0].primary_rgbs_ts=`uci -q get advancedplus.@theme[$i].primary_rgbs_ts`
					[ $mode = dark ] && uci set advancedplus.@basic[0].primary_rgbbody='33,45,60' || uci set advancedplus.@basic[0].primary_rgbbody='248,248,248'
				;;
				red)
					uci set advancedplus.@basic[0].bkuse=`uci -q get advancedplus.@theme[$i].bkuse`
					uci set advancedplus.@basic[0].primary_opacity='0'
					uci set advancedplus.@basic[0].primary_rgbm='143,32,13'
					uci set advancedplus.@basic[0].primary_rgbm_ts='0.9'
					uci set advancedplus.@basic[0].primary_rgbs='243,119,72'
					uci set advancedplus.@basic[0].primary_rgbs_ts=`uci -q get advancedplus.@theme[$i].primary_rgbs_ts`
					[ $mode = dark ] && uci set advancedplus.@basic[0].primary_rgbbody='33,45,60' || uci set advancedplus.@basic[0].primary_rgbbody='248,248,248'
				;;
				black)
					uci set advancedplus.@basic[0].bkuse=`uci -q get advancedplus.@theme[$i].bkuse`
					uci set advancedplus.@basic[0].primary_opacity='0'
					uci set advancedplus.@basic[0].primary_rgbm='25,25,26'
					uci set advancedplus.@basic[0].primary_rgbm_ts='0.9'
					uci set advancedplus.@basic[0].primary_rgbs='55,80,90'
					uci set advancedplus.@basic[0].primary_rgbs_ts=`uci -q get advancedplus.@theme[$i].primary_rgbs_ts`
					[ $mode = dark ] && uci set advancedplus.@basic[0].primary_rgbbody='33,45,60' || uci set advancedplus.@basic[0].primary_rgbbody='248,248,248'
				;;
				gray)
					uci set advancedplus.@basic[0].bkuse=`uci -q get advancedplus.@theme[$i].bkuse`
					uci set advancedplus.@basic[0].primary_opacity='5'
					uci set advancedplus.@basic[0].primary_rgbm='50,67,77'
					uci set advancedplus.@basic[0].primary_rgbm_ts='0.9'
					uci set advancedplus.@basic[0].primary_rgbs='64,68,70'
					uci set advancedplus.@basic[0].primary_rgbs_ts=`uci -q get advancedplus.@theme[$i].primary_rgbs_ts`
					[ $mode = dark ] && uci set advancedplus.@basic[0].primary_rgbbody='33,45,60' || uci set advancedplus.@basic[0].primary_rgbbody='248,248,248'
				;;
				bluets)
					uci set advancedplus.@basic[0].bkuse=`uci -q get advancedplus.@theme[$i].bkuse`
					uci set advancedplus.@basic[0].primary_opacity='3'
					uci set advancedplus.@basic[0].primary_rgbm='66,139,139'
					uci set advancedplus.@basic[0].primary_rgbm_ts='0.9'
					uci set advancedplus.@basic[0].primary_rgbs='55,103,128'
					uci set advancedplus.@basic[0].primary_rgbs_ts=`uci -q get advancedplus.@theme[$i].primary_rgbs_ts`
					[ $mode = dark ] && uci set advancedplus.@basic[0].primary_rgbbody='33,45,60' || uci set advancedplus.@basic[0].primary_rgbbody='248,248,248'
				;;
				*)
					uci set advancedplus.@basic[0].bkuse=`uci -q get advancedplus.@theme[$i].bkuse`
					uci set advancedplus.@basic[0].primary_opacity=`uci -q get advancedplus.@theme[$i].primary_opacity`
					uci set advancedplus.@basic[0].primary_rgbm=`echo $primary_rgbm | sed 's#(##; s#)##g; s#rgb##g; s#\,\ #\,#g;s#\ #\,#g;'`
					uci set advancedplus.@basic[0].primary_rgbm_ts=`uci -q get advancedplus.@theme[$i].primary_rgbm_ts`
					uci set advancedplus.@basic[0].primary_rgbs=`uci -q get advancedplus.@theme[$i].primary_rgbs | sed 's#(##; s#)##g; s#rgb##g; s#\,\ #\,#g;s#\ #\,#g;'`
					uci set advancedplus.@basic[0].primary_rgbs_ts=`uci -q get advancedplus.@theme[$i].primary_rgbs_ts`
					[ $mode = dark ] && uci set advancedplus.@basic[0].primary_rgbbody='33,45,60' || uci set advancedplus.@basic[0].primary_rgbbody='248,248,248'
				;;
			esac
			useset=1
			break
		fi
	done
	if [ "x$useset" == "x0" ] ; then
		uci set advancedplus.@basic[0].bkuse='0'
		uci set advancedplus.@basic[0].mode='auto'
		uci set advancedplus.@basic[0].primary_opacity='0'
		uci set advancedplus.@basic[0].primary_rgbm='20,109,179'
		uci set advancedplus.@basic[0].primary_rgbm_ts='0.9'
		uci set advancedplus.@basic[0].primary_rgbs='28,66,188'
		uci set advancedplus.@basic[0].primary_rgbs_ts='0.1'
		[ $mode == dark ] && uci set advancedplus.@basic[0].primary_rgbbody='33,45,60' || uci set advancedplus.@basic[0].primary_rgbbody='248,248,248'
	fi
	if [ "x$(uci -q get advancedplus.@basic[0].fontmode)" = "x1" ] ; then
		uci set advancedplus.@basic[0].font_d='1.3rem'
		uci set advancedplus.@basic[0].font_z='1.2rem'
		uci set advancedplus.@basic[0].font_x='1.1rem'
	else
		uci set advancedplus.@basic[0].font_d='1.0rem'
		uci set advancedplus.@basic[0].font_z='0.9rem'
		uci set advancedplus.@basic[0].font_x='0.8rem'
	fi
	uci commit advancedplus
}

start() {
	[ "x$(uci -q get advancedplus.@basic[0].mode)" = "x" ] && /etc/config/advancedplus reset
	kucatset
	rm -rf /tmp/luci*
}

stop() {
	rm -rf /tmp/luci*
}
